/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 developer.glb -T 
Files: developer.glb [981.62KB] > /Users/hsuwinlat/Desktop/jsm pj/threejscc-portfolio/public/models/developer-transformed.glb [395.08KB] (60%)
*/

import React, { useEffect, useRef } from 'react';
import { useGraph } from '@react-three/fiber';
import { useAnimations, useFBX, useGLTF } from '@react-three/drei';
import { SkeletonUtils } from 'three-stdlib';

const Developer = ({ animationName = 'idle', ...props }) => {
  const group = useRef();

  const { scene } = useGLTF('/models/animations/jan.glb');
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);

  const { animations: idleAnimation } = useFBX('/models/animations/idle.fbx');
  const { animations: saluteAnimation } = useFBX('/models/animations/salute.fbx');
  const { animations: clappingAnimation } = useFBX('/models/animations/clapping.fbx');
  const { animations: victoryAnimation } = useFBX('/models/animations/victory.fbx');

  idleAnimation[0].name = 'idle';
  saluteAnimation[0].name = 'salute';
  clappingAnimation[0].name = 'clapping';
  victoryAnimation[0].name = 'victory';

  const { actions } = useAnimations(
    [idleAnimation[0], saluteAnimation[0], clappingAnimation[0], victoryAnimation[0]],
    group,
  );

  // Debug: Log available nodes and materials
  useEffect(() => {
    console.log('=== JAN.GLB MODEL STRUCTURE ===');
    console.log('Available nodes:', Object.keys(nodes));
    console.log('Available materials:', Object.keys(materials));
    
    // Log each node with its properties
    Object.entries(nodes).forEach(([name, node]) => {
      console.log(`Node: ${name}`, {
        type: node.type,
        hasGeometry: !!node.geometry,
        hasMaterial: !!node.material,
        hasChildren: node.children?.length > 0,
        childrenCount: node.children?.length || 0
      });
    });
  }, [nodes, materials]);

  useEffect(() => {
    actions[animationName].reset().fadeIn(0.5).play();
    return () => actions[animationName].fadeOut(0.5);
  }, [animationName]);

  // Helper function to safely render a mesh if it exists
  const renderMesh = (nodeName, materialName, meshName) => {
    const node = nodes[nodeName];
    const material = materials[materialName];
    
    if (!node || !material) {
      return null;
    }

    return (
      <skinnedMesh
        key={nodeName}
        name={meshName || nodeName}
        geometry={node.geometry}
        material={material}
        skeleton={node.skeleton}
        morphTargetDictionary={node.morphTargetDictionary}
        morphTargetInfluences={node.morphTargetInfluences}
      />
    );
  };

  return (
    <group ref={group} {...props} dispose={null}>
      {/* Use the Hips bone as root (confirmed to exist in jan.glb) */}
      <primitive object={nodes.Hips} />
      
      {/* Render available meshes - only the ones that exist in jan.glb */}
      {renderMesh('Wolf3D_Hair', 'Wolf3D_Hair', 'Hair')}
      {renderMesh('Wolf3D_Body', 'Wolf3D_Body', 'Body')}
      {renderMesh('Wolf3D_Outfit_Bottom', 'Wolf3D_Outfit_Bottom', 'OutfitBottom')}
      {renderMesh('Wolf3D_Outfit_Footwear', 'Wolf3D_Outfit_Footwear', 'Footwear')}
      {renderMesh('Wolf3D_Outfit_Top', 'Wolf3D_Outfit_Top', 'OutfitTop')}
      {renderMesh('EyeLeft', 'Wolf3D_Eye', 'EyeLeft')}
      {renderMesh('EyeRight', 'Wolf3D_Eye', 'EyeRight')}
      {renderMesh('Wolf3D_Head', 'Wolf3D_Skin', 'Head')}
      {renderMesh('Wolf3D_Teeth', 'Wolf3D_Teeth', 'Teeth')}
    </group>
  );
};

useGLTF.preload('/models/animations/jan.glb');

// Preload animations to reduce loading warnings
useFBX.preload('/models/animations/idle.fbx');
useFBX.preload('/models/animations/salute.fbx');
useFBX.preload('/models/animations/clapping.fbx');
useFBX.preload('/models/animations/victory.fbx');

export default Developer;
